# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
