# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20170317_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 21, 10, 38, 22, 913180)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 10, 38, 22, 913894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 10, 38, 22, 913851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_days',
            field=models.IntegerField(blank=True),
        ),
    ]
