# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20170322_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 3, 49, 59, 766563)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 3, 49, 59, 767277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 3, 49, 59, 767234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
