# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20170323_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 24, 3, 7, 51, 636452)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Book'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('rented', 'Rented'), ('completed', 'Completed')], default='rented', max_length=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
        ),
    ]
