# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20170324_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 27, 9, 4, 59, 105793)),
        ),
    ]
